version: '3'

services:
  app:
    build: ./app
    container_name: flask_app
    volumes:
      - ./app:/app
    expose:
      - 5000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app