version: '3'

services:
  app:
    build: ./app
    container_name: flask_app
    volumes:
      - ./app:/app
    expose:
      - 5000
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app