global:
  scrape_interval: 3s

  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "webapp"
    static_configs:
      - targets: ["app:5000"] 
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']