global:
  scrape_interval: 5s 
  evaluation_interval: 5s 
    monitor: 'app'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:5000
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
  